Criar botao
MateusLeiros/PickAPokemonCard pull request #3
Opened 2024-12-11 23:24 UTC by MateusLeiros

Botão de Sign in criado e estilizado de acordo com modelo do Figma.

2024-12-12 01:13 UTC, TrainedLoop requested changes
não conhecia essa gambi do mimimi;modules.css interessante

2024-12-12 01:13 UTC, TrainedLoop commented on src/components/Button.module.css
> +    padding: 0 30px;
tem 3 coisas dando largura a esse botão
o padding lateral, o space arround e o próprio width, tenta pensar em uma caixinha dentro da outra falicita a não ter um monte de css fazendo a mesma coisa, eu tenho o costume de botar borda em tudo pra ir vendo como se comporta, pode ser que te ajude. mas segue um desenho do que estou falando
![image](https://github.com/user-attachments/assets/fb3c134c-2cf4-4d89-9881-f98cb9a6ff1e)

tenta sempre pensar em qual será a melhor forma de botar espaçamento pra cada contêiner desse.
sempre tenta estressar o layout principalmente na largura, esse botão poderia ser mais largo em alguns casos, ter um icone diferente ou um texto maior. como vai se comportar?

2024-12-12 01:13 UTC, TrainedLoop commented on src/components/Button.module.css
> +    padding-top: 0px;
padding de 0 não faz nada

2024-12-12 01:13 UTC, TrainedLoop commented on src/components/Button.module.css
> +    display: inline-block;
por que do inline-block?

2024-12-12 01:25 UTC, MateusLeiros commented on src/index.css
> +}
eu só criei um tipo de moldura pra pagina principal. Ela tem um tamanho máximo (caso a janela esteja aberta em um monitor grande) e centralizei com essa margem. Não é nada que faça grande diferença nesse momento, mas eu pensei pro futuro de fazer a pagina centralizada ao inves de tomar toda a área do browser

2024-12-12 01:26 UTC, MateusLeiros commented on src/components/Button.tsx
> +        </div>
Verdade, acho que foi o costume de deixar uma div pra encapsular tudo. Eu sempre criava componentes com a div pra caso tivesse mais html ali dentro. Mas nesse caso faz sentido tirar.

2024-12-12 01:27 UTC, MateusLeiros commented on src/components/Button.module.css
> +    position: relative;
Esse position relative faz parte do "coloquei em algum momento e esqueci de tirar"... My bad, vou corrigir

2024-12-12 01:29 UTC, MateusLeiros commented on src/components/Button.module.css
> +    vertical-align: middle;
Hmm... vou dar uma melhorada nesse css então... Eu cheguei a testar ele com flexbox e de todas as formas o texto sempre ficava desalinhado com a imagem, e eu só achei essa forma de alinhar um pouco melhor... Vou dar uma lida nessa página com mais calma.

2024-12-12 01:34 UTC, TrainedLoop commented on src/index.css
> +}
60 rem foi um numero arbitrário no meu monitor ficou bem longe do centro.
Vc poderia usar o flexbox mesmo pra alinhas as coisas horizontalmente, margin 0 auto e como os homens das cavernas alinhavam as coisas;

2024-12-12 01:37 UTC, TrainedLoop commented on src/index.css
> +}
![image](https://github.com/user-attachments/assets/ac1f0253-daf2-4165-8d0a-925ff5c3694c)

2024-12-12 02:31 UTC, MateusLeiros commented on src/components/Button.module.css
> +    display: inline-block;
Isso fui eu tentando fazer os itens ficarem um ao lado do outro dentro do botão (o icone estava ficando em cima do texto).

2024-12-12 14:41 UTC, TrainedLoop requested changes

2024-12-12 14:41 UTC, TrainedLoop commented on src/App.tsx
> +import Button from './components/Button.tsx';
Colocar todas as props que discutirmos pra funcionar

2024-12-29 16:06 UTC, TrainedLoop requested changes

2024-12-29 16:06 UTC, TrainedLoop commented on src/test.tsx
> +      />
procura sobre no css sobre text-overflow é uma saída melhor

2024-12-29 16:06 UTC, TrainedLoop commented on src/test.tsx
> +      />
pode apagar esses 3

2024-12-29 16:06 UTC, TrainedLoop commented on src/test.tsx
> +    </div>
bota pra funcionar esses 2, o isLoading não está sendo respeitado e o ícone não está sendo passado pro botão

2024-12-29 16:06 UTC, TrainedLoop commented on src/components/Button.module.css
> +}
repensa esse css aqui, tem muita coisa aqui pra esse texto o text-overflow precisa estar acompanhado de um "overflow" se não perde o sentido 
![image](https://github.com/user-attachments/assets/5e984cb5-0628-46b9-acbc-24fe5fefbb13)
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

antes de tacar um css na pagina, tenta entender o que ele ta fazendo não é jogo de tentativa e erro tem um por que

2024-12-29 16:06 UTC, TrainedLoop commented on src/components/Button.tsx
> +
no teu vscode não ta reclamando?

2024-12-29 16:36 UTC, TrainedLoop commented on src/components/Button.module.css
> +}
mais uma coisa

observa esses espaçamentos
![image](https://github.com/user-attachments/assets/5de74852-cfb0-4b66-91d6-438a20bcad4c)

cada um está de um tamanho

2024-12-29 16:36 UTC, TrainedLoop commented on src/components/Button.module.css
> +}
o espaçmento entre a borda e o inicio do conteúdo deveria ser fixo, assim como o espaçamento entre o ícone e o texto

2024-12-29 18:16 UTC, MateusLeiros commented on src/components/Button.module.css
> +}
Aqui eu tive um problema sério com o botão de texto gigante. Basicamente todos os botões estavam respondendo corretamente e tudo tava da forma ideal, mas esse botão estava fazendo o svg sumir. Eu tentei várias formas diferentes de organizar os flex children, só o space evenly fez o svg aparecer, mas eu também fiquei um pouco incomodado com esse espaçamento irregular.

2024-12-29 18:42 UTC, MateusLeiros commented on package.json
> +    "@svgr/webpack": "^8.1.0",
Eu não tava conseguindo importar SVG de jeito nenhum. Achei vários lugares falando pra instalar webpack ou outros parecidos pra fazer rodar svg. Tava sempre dando um erro estranho. Talvez eu tenha instalado mais de um e não esteja usando eles. Só funcionou depois de colocar aquele "?react" no final do nome do arquivo.

2024-12-29 18:44 UTC, MateusLeiros commented on src/components/Button.tsx
> +    }
O 2000 foi bom saber, pq realmente tava marcando como errado no meu vscode, não me atentei que eu tava inserindo uma array.
Sobre o loading, eu sei que eu botei um timer fixo. Eu não tava lembrando como fazer pra o Loading começar no inicio do fetch e terminar quando acabasse o fetch. To pesquisando isso agora.

2024-12-29 18:50 UTC, MateusLeiros commented on src/components/Button.tsx
> +
Tava sim. Parece que desse passo a passo que vc mandou, só faltou eu adicionar uma linha no vite-env.d.ts. Mas estranhamente tava funcionando. Ele parou de reclamar mas não mudou nada.

2024-12-29 22:42 UTC, merged